name: Push logged metrics
description: Push logged metrics
inputs:
  metricsKey:
    description: Private key for signing messages
    required: true
runs:
  using: composite
  steps:
    - name: Transform and push metrics
      continue-on-error: true
      shell: bash
      run: |
        set -euo pipefail
        
        bash "$GITHUB_ACTION_PATH/scripts/transform.sh" \
          --log-file ".sfpowerscripts/logs/metrics.log" \
          --strict \
          --config "$GITHUB_ACTION_PATH/config/metrics_config.json" \
          --fail-on-warn \
          --error-prefix "error:: " \
          --warn-prefix "warning:: " \
          --output "promMetrics.log"

        if [[ "${DISABLE_SF_METRICS_PUSH:-false}" == "true" ]]; then
          echo "DISABLE_SF_METRICS_PUSH is set to true. Skipping metrics push..."
          exit 0
        fi

        bash "$GITHUB_ACTION_PATH/scripts/pushMetrics.sh" \
          --endpoint "$ENDPOINT" \
          --log-group-prefix "::group::" \
          --log-group-suffix "::endgroup::" \
          --metrics-file "promMetrics.log" \
          --runner-name "${GITHUB_REPOSITORY##*/}"

      env:
        METRICS_KEY: ${{ inputs.metricsKey }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        ENDPOINT: https://sf-github-metrics.ekstern.dev.nav.no/measures/job/sfplatform
        # Optional overrides:
        # MAX_BYTES: "2000000"